import type { NextPage, GetStaticProps } from 'next'
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head'

import styles from '../styles/Home.module.css'

import { CourseList } from '../components/courseList';
import { Banner } from '../components/Banner';
import { Header } from '../components/Header';
import { basePT, baseEN } from '../services/airtable';

interface homeProps {
  data: dataProps[]
}

interface dataProps {
  title: string;
  path: string;
  image: {
    url: string;
  }[];
}

export default function Home({ data }: homeProps) {
  const { t } = useTranslation('home');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header
          headerTitle={t("title")} 
          buttonName={t("buttonName")}
        />
        <Banner BannerTitle={t("bannerTitle")} />
        <CourseList
          courseData={data}
          buttonName={t("buttonCardTitle")}
        />
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const stringLocale = locale ? locale : "";

  let data: any;

  if (stringLocale === "pt") {
    const records = await basePT('courses').select({}).all();

    data = records
      .map((item) => {
        return {
          title: item.fields.name,
          path: item.fields.path,
          image: item.fields.image
        };
      });
  }

  if (stringLocale === "en") {
    const records = await baseEN('courses').select({}).all();

    data = records
      .map((item) => {
        return {
          title: item.fields.name,
          path: item.fields.path,
          image: item.fields.image
        };
      });
  }

  return {
    props: {
      data,
      ...(await serverSideTranslations(stringLocale, ['home'])),
    },
    revalidate: 60 // 1 minuto
  };
}
